---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  #vars_files:
  #  - ../../defaults/main.yml
  #vars:


  tasks:
    - name: "Include ntp_client"
      include_role:
        name: "ntp_client"

  #roles:
    #- role: habbis.ntp_client
